### ISSUE TITLE
RadiologyRequestForm issues

### ISSUE THREAD

**Issue by ir4y** [beda-software/smart-form-ide#1]
During mapping from https://github.com/beda-software/smart-form-ide/blob/main/resources/Questionnaire/RadiologyRequestForm.json to https://build.fhir.org/ig/hl7au/au-fhir-erequesting/StructureDefinition-au-erequesting-servicerequest.html
This FHIRMappingLanguage script was produced: https://github.com/beda-software/smart-form-ide/blob/main/resources/maps/radiology.map

The resulted ServiceRequest is cont compliant to au-erequesting-servicerequest because of the following issues:
- [x] requisition Local Order Identifier is required but there is no related field in the questionnaire
- [x] RadiologyRequestForm requests patient, encounter via launchContext but it doesn't store this information in hidden fields, so we can't use it to extract subject and encounter
- [x] au-erequesting-servicerequest profile requires requester to be a PractitionerRole, while RadiologyRequestForm request practitioner resources via launchContext.
- [x] radiology-service-examination-timing should have a dateTime type

It is not clear how to map:
- [x] radiology-service-examination-contrast
- [x] radiology-service-clinicalnotes (there is radiology-service-comment, what is the difference between them)
- [x] radiology-provider

There is an issue with mapping two repeatable groups radiology-service and radiology-service-examination into flatten list of service requests

**Comment by fongsean** [comment]
For task 2, as discussed you can grab the patient from the launchContext and put it in QuestionnaireResponse.subject.

See https://github.com/aehrc/smart-forms/blob/b76be274b0f198a0eb61f605d349a5e5da59be14/packages/sdc-populate/src/SDCPopulateQuestionnaireOperation/utils/constructResponse.ts#L128-L145. This is code from our $populate library, but in your case you might have to add this logic in the sdc-ide app itself.

**Comment by liambarnes** [comment]
Here's an updated form https://smartforms.csiro.au/api/fhir/Questionnaire/RadiologyRequestForm/_history/2

### Issues noted in the initial comment:

**1. requisition Local Order Identifier**
- Item added (linkId = "radiology-order-number") that can be mapped to requisition.value
- Map can hard code requisition.system as "https://smartforms.csiro.au/id/DiagnosticOrder"
- Map can hard code requisition.assigner.display as "AEHRC CSIRO"

**2. RadiologyRequestForm launchContext**
- refer to Sean's [comment](https://github.com/beda-software/smart-form-ide/issues/1#issuecomment-2216604030) above.

**3. requester as PractitionerRole**
- Item added (linkId = "radiology-order-requesterreference") that can be mapped to requester.reference
- Item added (linkId = "radiology-order-requesterdisplay") that can be mapped to requester.display

**4. radiology-service-examination-timing should have a dateTime type**
- Updated to dateTime

### Clarification points:

**1. radiology-service-examination-contrast**
- leave unmapped (will address in form at a later stage)

**2. radiology-service-clinicalnotes**
- also maps to ServiceRequest.note

**3. radiology-provider**
- Item has been removed for simplicity

**Comment by ir4y** [comment]
All changes has been applied
